<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0-beta.1" />
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="RabbitMQ.Client" Version="6.7.0" />
    </ItemGroup>

</Project>
