<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <ItemGroup>
  <ProjectReference Include="..\inmind_session5_DDD.Common\inmind_session5_DDD.Common.csproj" />
  <ProjectReference Include="..\inmind_session5_DDD.Domain\inmind_session5_DDD.Domain.csproj" />
  <ProjectReference Include="..\inmind_session5_DDD.Persistence\inmind_session5_DDD.Persistence.csproj" />
  <ProjectReference Include="..\inmind_session5_DDD.Application\inmind_session5_DDD.Application.csproj" /> 
</ItemGroup>


    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

</Project>
